name: WakaTime Stats

on:
  schedule:
    - cron: "0 0 * * *" # every midnight
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 👈 important
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_BAR: true
          COMPACT: true
